# Generated by Django 2.2.2 on 2019-07-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1, verbose_name=((0, '上线'), (1, '下线')))),
                ('name', models.CharField(max_length=100, unique=True)),
                ('img', models.ImageField(upload_to='./static/images/focus/')),
                ('href', models.CharField(max_length=256)),
                ('create_data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '首页轮播',
                'db_table': 'images',
            },
        ),
    ]
