# Generated by Django 2.2.2 on 2019-07-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1, verbose_name=((0, '上线'), (1, '下线')))),
                ('weight', models.IntegerField(default=0, verbose_name='权重')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='新闻标题')),
                ('summary', models.CharField(default='summary', max_length=40, verbose_name='简介')),
            ],
            options={
                'verbose_name_plural': '首页公告',
                'db_table': 'News',
            },
        ),
        migrations.AlterModelTable(
            name='images',
            table='Images',
        ),
    ]
