# Generated by Django 2.2.2 on 2019-07-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20190715_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.CharField(default='新闻内容', max_length=1000, verbose_name='内容'),
        ),
    ]
