# Generated by Django 2.2.2 on 2019-07-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20190715_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Superman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1, verbose_name=((0, '上线'), (1, '下线')))),
                ('weight', models.IntegerField(default=0, verbose_name='权重')),
                ('img', models.ImageField(upload_to='./static/images/superman/')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='村民干部')),
                ('summary', models.CharField(default='个人简介', max_length=100, verbose_name='简介')),
            ],
            options={
                'verbose_name_plural': '村民干部',
                'db_table': 'Superman',
            },
        ),
    ]
