# Generated by Django 2.2.2 on 2019-07-16 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_classification_direction_level_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='Vedio',
        ),
    ]
